.TH "playlist.h" 3 "Wed Nov 12 2014" "Blokbox" \" -*- nroff -*-
.ad l
.nh
.SH NAME
playlist.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QWidget>\fP
.br
\fC#include <QMediaPlaylist>\fP
.br
\fC#include 'playlistmodel\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPlaylist\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBUi\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Blokbox from the source code\&.
